Add initial support for IRIX/mips.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,7 +21,7 @@ TMPS="${TMPDIR1}/cpuinfo-conf-${RANDOM}-$$-${RANDOM}.S"
 # default parameters
 prefix="/usr"
 libdir=""
-cc="gcc"
+cc="cc"
 build_static="no"
 build_shared="no"
 install_sdk="no"
@@ -50,6 +50,9 @@ sparc64)
 x86_64|amd64)
     host_cpu="x86_64"
     ;;
+IP35)
+    host_cpu="mips"
+    ;;
 *)
     host_cpu="unknown"
     ;;
@@ -57,6 +60,9 @@ esac
 case "$host_os" in
 cygwin*)
     host_os="windows"
+    ;;
+irix*)
+    host_os="irix"
     ;;
 esac
 
@@ -164,6 +170,30 @@ if $cc -Werror -S $TMPC -o $TMPS >/dev/null 2>&1; then
 fi
 rm -f $TMPC $TMPS
 
+# check for compiler type
+cat > $TMPC << EOF
+#include <stdio.h>
+#if defined __INTEL_COMPILER
+#define COMPILER_NAME "icc"
+#elif defined __GNUC__
+#define COMPILER_NAME "gcc"
+#elif defined __sgi && _SGI_COMPILER_VERSION > 0
+#define COMPILER_NAME "mipspro"
+#else
+#define COMPILER_NAME "unknown"
+#endif
+int main(void)
+{
+    printf("%s\n", COMPILER_NAME);
+    return 0;
+}
+EOF
+compiler="unknown"
+if $cc $TMPC -o $TMPE >/dev/null 2>&1; then
+    compiler=`$TMPE`
+fi
+rm -f $TMPC $TMPE
+
 # check for compiler flag
 check_cc_option() {
     echo "int i;" > $TMPC
@@ -174,6 +204,16 @@ check_cc_option() {
     rm -f $TMPC
     return 1
 }
+
+# check for C99 support
+if test "$compiler" = "mipspro"; then
+    if check_cc_option -c99; then
+	cc="$cc -c99"
+    else
+	echo "ERROR: Unsupported C compiler, try with a C++ compiler?"
+	exit 1
+    fi
+fi
 
 # check for CFLAGS
 if test -z "$CFLAGS"; then
@@ -187,6 +227,9 @@ if test "$biarch" = "yes" -a -z "$CFLAGS_32"; then
     if check_cc_option -mtune=generic $CFLAGS_32; then
 	CFLAGS_32="$CFLAGS_32 -mtune=generic"
     fi
+fi
+if check_cc_option -Wall; then
+    CFLAGS="$CFLAGS -Wall"
 fi
 
 # print configure help
@@ -233,6 +276,7 @@ echo "/* Automatically generated by configure - do not modify */" > $config_h
 
 echo "CC=$cc" >> $config_mak
 echo "CFLAGS=$CFLAGS" >> $config_mak
+echo "COMPILER=$compiler" >> $config_mak
 if test "$host_os" = "linux"; then
     echo "OS=linux" >> $config_mak
     echo "#define HOST_LINUX 1" >> $config_h
@@ -257,8 +301,12 @@ elif test "$host_os" = "windows"; then
     echo "OS=windows" >> $config_mak
     echo "#define HOST_WINDOWS 1" >> $config_h
     echo "#define HOST_OS \"windows\"" >> $config_h
+elif test "$host_os" = "irix"; then
+    echo "OS=irix" >> $config_mak
+    echo "#define HOST_IRIX 1" >> $config_h
+    echo "#define HOST_OS \"irix\"" >> $config_h
 else
-    echo "Unsupported OS"
+    echo "ERROR: Unsupported OS"
     exit 1
 fi
 if test "$host_cpu" = "i386" ; then
@@ -281,8 +329,13 @@ elif test "$host_cpu" = "ppc64" ; then
     echo "CPUINFO_ARCH=ppc" >> $config_mak
     echo "#define HOST_PPC64 1" >> $config_h
     echo "#define HOST_ARCH \"ppc64\"" >> $config_h
+elif test "$host_cpu" = "mips" ; then
+    echo "ARCH=mips" >> $config_mak
+    echo "CPUINFO_ARCH=mips" >> $config_mak
+    echo "#define HOST_MIPS 1" >> $config_h
+    echo "#define HOST_ARCH \"mips\"" >> $config_h
 else
-    echo "Unsupported CPU"
+    echo "ERROR: Unsupported CPU"
     exit 1
 fi
 
